chat/urls.py
# from django.urls import path, re_path

from django.conf.urls import  url
from .views import ThreadView, InboxView

# app_name = 'chat'
# urlpatterns = [
#     path("", InboxView.as_view()),
#     re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
# ]

urlpatterns = [
    url(r'^$', InboxView.as_view(), name="inbox_view"),
    url(r'^(?P<username>[\w.@+-]+)/$', ThreadView.as_view(), name="thread_view"),

]

chat/models.py
from accounts.models import LeadUser, Trainer, Client
from appsettings.models import WELCOME_MESSAGE
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
import json

User = get_user_model()

class ThreadManager(models.Manager):
    def get_or_new(self, leaduser, client, trainer):
        obj = self.model(leaduser=leaduser, client=client, trainer=trainer)
        thread_qs = Thread.objects.filter(leaduser=leaduser, client=client, trainer=trainer)
        if thread_qs.exists():
            return thread_qs.first(), True
        else:
            obj.save()
            return obj, True


class Thread(models.Model):
    leaduser     = models.ForeignKey(LeadUser, null=True, blank=True)
    client       = models.ForeignKey(Client, null=True, blank=True)
    trainer      = models.ForeignKey(Trainer, null=True, blank=True)
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)

    objects      = ThreadManager()

    def __str__(self):
        return "%s" % self.id

    @property
    def room_group_name(self):
        return 'chat_{0}'.format(self.id)

    def is_first_for_leaduser(self):
        if self.leaduser.thread_set.all().count() >= 1:
            return False
        return True


def trigger_welcome_message(client, trainer):

    data = {
        "type": "welcome_message",
        "client_id": client.id,
        "trainer_id": trainer.id,
        "userhandle": 'trainer',
        "timeout": 180
    }
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.send)('welcome', data)


@receiver(post_save, sender=Client)
def welcome_message_post_save(instance, created, **kwargs):
    if created:
        client = instance
        trainer = Trainer.objects.get(is_boss=True)
        trigger_welcome_message(client, trainer)
    return


class Status(models.Model):
    leaduser    = models.ForeignKey(LeadUser, null=True, blank=True)
    client      = models.ForeignKey(Client, null=True, blank=True)
    trainer     = models.ForeignKey(Trainer, null=True, blank=True)


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    leaduser    = models.ForeignKey(LeadUser, null=True, blank=True)
    client      = models.ForeignKey(Client, null=True, blank=True)
    trainer     = models.ForeignKey(Trainer, null=True, blank=True)
    message     = models.TextField(null=True, blank=True)
    userhandle  = models.CharField(max_length=120, null=True, blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    created     = models.DateField(auto_now_add=True, auto_now=False)
    updated     = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['created']

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} via {{ chat.user }}</li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script>
$(document).ready(function(){
    var formData = $("#form")
    var messageInput = $("#id_message")
    var chatItems = $('#chat-items')
    var loc = window.location
    var wsStart = "ws://"
    if (loc.protocol == "https:"){
        wsStart = "wss://"
    }
    var webSocketEndpoint =  wsStart + loc.host + loc.pathname + '/' // ws : wss
    var socket = new WebSocket(webSocketEndpoint)

    socket.onmessage = function(e){
        console.log('message', e)
        // alert(e.data)
        var msgData = JSON.parse(e.data)
        console.log(msgData)
        chatItems.append(`<li>${msgData.msg} via ${msgData.user}</li>`)
    }

    socket.onopen = function(e){
        console.log('open', e)
        formData.submit(function(event){
            event.preventDefault()
            var messageText = messageInput.val()
            console.log(messageText)
            var jsonData = JSON.stringify({msg: messageText, user:'jmitchel3'})
            socket.send(jsonData)
            formData[0].reset()
        })
    }

    socket.onerror = function(e){
        console.log('error', e)
    }
    socket.onclose = function(e){
        console.log('closed', e)
    }




    if (socket.readyState == WebSocket.OPEN) {

    } else if (socket.readyState == WebSocket.CONNECTING){
        console.log("connecting..")
    }


})

</script>
{% endblock %}