chat/urls.py
# from django.urls import path, re_path

from django.conf.urls import  url
from .views import ThreadView, InboxView

# app_name = 'chat'
# urlpatterns = [
#     path("", InboxView.as_view()),
#     re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
# ]

urlpatterns = [
    url(r'^$', InboxView.as_view(), name="inbox_view"),
    url(r'^(?P<username>[\w.@+-]+)/$', ThreadView.as_view(), name="thread_view"),

]

subscriptions/urls.py
from django.conf.urls import  url
from .views import (
    program_feature_add,
    program_feature_delete,
    program_price_add,
    program_price_delete,
    ProgramCreateView,
    ProgramDetailView,
    ProgramListView,
    ProgramUpdateView,
    ProgramDeleteView,
    program_workout_delete,
    WorkoutTemplateCreateView,
    WorkoutTemplateDeleteView,
    WorkoutTemplateUpdateView,
    WsetTemplateCreateView,
    training_template_create,
    training_template_delete,
    CustomWorkoutUpdateView,
    CustomWorkoutDeleteView,
    CustomWsetCreateView,
    CustomWsetUpdateView,
    CustomWorkoutCreateView,
    custom_training_create,
    custom_training_delete,
    FoodProgramTemplateCreateView,
    FoodProgramTemplateDetailView,
    FoodProgramTemplateUpdateView,
    FoodProgramTemplateDeleteView,
    food_template_create,
    food_template_delete,
        )

urlpatterns = [
    ## PROGRAMS
    url(r'^programs/$', ProgramListView.as_view(), name="program_list"),
    url(r'^programs/create/$', ProgramCreateView.as_view(), name="program_create"),
    url(r'^programs/(?P<pk>\d+)/detail/$', ProgramDetailView.as_view(), name="program_detail"),
    url(r'^programs/(?P<pk>\d+)/update/$', ProgramUpdateView.as_view(), name="program_update"),
    url(r'^programs/(?P<pk>\d+)/delete/$', ProgramDeleteView.as_view(), name="program_delete"),
    url(r'^workout-delete/$', program_workout_delete, name="program_workout_delete"),
    url(r'^programs/(?P<pk>\d+)/update/price-add$', program_price_add, name="program_price_add"),
    url(r'^programs/(?P<pk>\d+)/update/price-delete$', program_price_delete, name="program_price_delete"),
    url(r'^programs/(?P<pk>\d+)/update/feature-add$', program_feature_add, name="program_feature_add"),
    url(r'^programs/(?P<pk>\d+)/update/feature-delete$', program_feature_delete, name="program_feature_delete"),

    ## WORKOUT TEMPLATES
    url(r'^programs/(?P<pk>\d+)/update/workout-templates/create/$', WorkoutTemplateCreateView.as_view(), name="workout_template_create"),
    url(r'^programs/(?P<pk>\d+)/update/workout-templates/(?P<id>\d+)/update/$', WorkoutTemplateUpdateView.as_view(), name="workout_template_update"),
    url(r'^programs/(?P<pk>\d+)/update/workout-templates/(?P<id>\d+)/delete/$', WorkoutTemplateDeleteView.as_view(), name="workout_template_delete"),
    url(r'^workout-templates/(?P<pk>\d+)/update/wset-templates/create/$', WsetTemplateCreateView.as_view(), name="wset_template_create"),
    url(r'^wset-templates/training-template-create/$', training_template_create, name="training_template_create"),
    url(r'^wset-templates/training-template-delete/$', training_template_delete, name="training_template_delete"),

    ## CUSTOM WORKOUT TEMPLATES
    url(r'^programs/(?P<pk>\d+)/update/custom-workout/create/$', CustomWorkoutCreateView.as_view(), name="custom_workout_create"),
    url(r'^custom-workout/(?P<pk>\d+)/update/$', CustomWorkoutUpdateView.as_view(), name="custom_workout_update"),
    url(r'^custom-workout/(?P<pk>\d+)/delete/$', CustomWorkoutDeleteView.as_view(), name="custom_workout_delete"),
    url(r'^custom-workout/(?P<pk>\d+)/update/custom-wset/create/$', CustomWsetCreateView.as_view(), name="custom_wset_create"),
    url(r'^custom-workout/(?P<pk>\d+)/update/custom-wset/(?P<sk>\d+)/update/$', CustomWsetUpdateView.as_view(), name="custom_wset_update"),
    url(r'^custom-wset-templates/custom-training-create/$', custom_training_create, name="custom_training_create"),
    url(r'^custom-wset-templates/custom-training-delete/$', custom_training_delete, name="custom_training_delete"),

    ## FOODPROGRAM TEMPLATES
    url(r'^programs/(?P<pk>\d+)/update/foodprogram-templates/create/$', FoodProgramTemplateCreateView.as_view(), name="foodprogram_template_create"),
    url(r'^programs/(?P<pk>\d+)/update/foodprogram-templates/(?P<id>\d+)/detail/$', FoodProgramTemplateDetailView.as_view(), name="foodprogram_template_detail"),
    url(r'^programs/(?P<pk>\d+)/update/foodprogram-templates/(?P<id>\d+)/update/$', FoodProgramTemplateUpdateView.as_view(), name="foodprogram_template_update"),
    url(r'^programs/(?P<pk>\d+)/update/foodprogram-templates/(?P<id>\d+)/delete/$', FoodProgramTemplateDeleteView.as_view(), name="foodprogram_template_delete"),
    url(r'^programs/food-template-create/$', food_template_create, name="food_template_create"),
    url(r'^programs/food-template-delete/$', food_template_delete, name="food_template_delete"),
]

subscriptions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from accounts.models import (
    SEX,
    LEVELS,
    )
from accounts.workout_models import (
    Training,
    Workout,
    Wset,
    )
from appsettings.models import (
    MainMuscle,
    OtherMuscle,
    ExerciseType,
    SettingsRestTime,
    PROGRAM_TYPE_CHOICES,
    SettingsTime,
    SettingsDay,
    Biomech,
    Vektor,
    DifficultyLevel,
    Equipment,
    WorkoutOccupation,
    PROGRAM_LOCATION,
    PROGRAM_LEVEL,
    )
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import now
from options.models import (
    Muscle,
    Exercise,
    Product,
    )

#############################################################################################################################
## HELP FUNCS

def program_uploads(instance, filename, *args, **kwargs):
    return 'programs/%s' % filename

#############################################################################################################################
## WORKOUT PROGRAMS

class Category(models.Model):
    parent_category = models.ForeignKey('self', null=True, blank=True)
    name = models.CharField(max_length=255)
    img = models.ImageField(upload_to=program_uploads, default='programs/program_bg.png')
    desc = models.TextField()
    rating = models.PositiveIntegerField(default=1)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse("members:category_detail", kwargs = {"pk":self.id})

    def get_member_food_absolute_url(self):
        return reverse("members:food_category_detail", kwargs = {"pk":self.id})


class Program(models.Model):
    is_active = models.BooleanField(default=False)
    category = models.ManyToManyField(Category, blank=False)
    demo = models.BooleanField(default=False)
    name = models.CharField(max_length=255, null=True, blank=False)
    short_desc = models.TextField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    img = models.ImageField(upload_to=program_uploads, default='programs/program_bg.png')
    video = models.URLField(max_length=250, blank=True, null=True)
    program_type = models.CharField(max_length=2, choices=PROGRAM_TYPE_CHOICES, null=True, blank=False)
    program_location = models.CharField(max_length=25, choices=PROGRAM_LOCATION, null=True, blank=False)
    program_level = models.CharField(max_length=25, choices=PROGRAM_LEVEL, null=True, blank=False)
    content_owner = models.ForeignKey('accounts.Trainer', on_delete=models.SET_NULL, null=True, blank=True)
    rating = models.PositiveIntegerField(default=1)
    recommend = models.BooleanField(default=False)
    to_all = models.BooleanField(default=False)
    daily = models.BooleanField(default=False)
    chargeable = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "%s" % self.name

    def get_update_url(self):
        return reverse("subscriptions:program_update", kwargs = {"pk":self.id})

    def get_detail_url(self):
        if self.program_type == 'WP' or self.program_type == 'FP' or self.program_type == 'FG':
            return None
        else:
            return reverse("subscriptions:program_detail", kwargs = {"pk":self.id})

    def get_memberzone_detail_url(self):
        if self.program_type == 'WC' or self.program_type == 'WG':
            return reverse("members:member_program_detail", kwargs = {"pk":self.id})
        return None

    def get_memberzone_food_detail_url(self):
        if self.program_type == 'FG':
            return reverse("members:member_foodprogram_detail", kwargs = {"pk":self.id})
        return None


    def get_delete_url(self):
        return reverse("subscriptions:program_delete", kwargs = {"pk":self.id})

    def get_program_workout_delete_url(self):
            return reverse("subscriptions:program_workout_delete")

    def get_program_type(self):
        if self.program_type == 'WP':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[0][1])
        elif self.program_type == 'FP':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[1][1])
        elif self.program_type == 'WG':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[2][1])
        elif self.program_type == 'WC':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[3][1])
        elif self.program_type == 'FG':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[4][1])
        elif self.program_type == 'MT':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[5][1])
        elif self.program_type == 'EX':
            return '{0}'.format(PROGRAM_TYPE_CHOICES[6][1])

    def price_type(self):
        if self.chargeable:
            return '{0}'.format('Да')
        else:
            return '{0}'.format('Нет')

    def get_number_exercises(self):
        lst = []
        for workout in self.workout_set.all():
            for wset in workout.wset_set.all():
                lst.append(wset.training_set.all().count())
        return sum(lst)

    def get_number_workouts(self):
        return self.workout_set.all().count()


class Feature(models.Model):
    program = models.ForeignKey(Program, null=True, blank=False)
    name = models.CharField(max_length=255, null=True, blank=False)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "%s" % self.name

# class Price(models.Model):
#     program = models.ForeignKey(Program, null=True, blank=False)
#     name = models.CharField(max_length=255, null=True, blank=False)
#     price = models.PositiveIntegerField(default=0)
#     number = models.PositiveIntegerField(default=1, blank=True)
#     created = models.DateField(auto_now_add=True, auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False, auto_now=True)

#     class Meta:
#         ordering = ['-created']

#     def __str__(self):
#         return "%s" % self.name


class Favourite(models.Model):
    program = models.ForeignKey(Program)
    client = models.ForeignKey('accounts.Client')
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['program']

    def __str__(self):
        return "%s | %s" % (self.program, self.client)


#############################################################################################################################
## WORKOUT TEMPLATES

class WorkoutTemplate(models.Model):
    program = models.ForeignKey(Program, null=True, blank=False)
    number = models.PositiveIntegerField(default=1)
    name = models.CharField(max_length=255, null=True, blank=False)
    sex = models.CharField('Пол', max_length=1, choices=SEX, null=True, blank=True)
    training_level = models.CharField('Уровень физ подготовки', max_length=4, choices=LEVELS, null=True, blank=True)
    rest = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return "%s:%s" % (self.name, self.created)

    def get_update_url(self):
        return reverse("subscriptions:workout_template_update", kwargs = {'pk':self.program.id, "id":self.id})

    def get_detail_url(self):
        return reverse("subscriptions:workout_template_detail", kwargs = {'pk':self.program.id, "id":self.id})

    def get_delete_url(self):
        return reverse("subscriptions:workout_template_delete", kwargs = {'pk':self.program.id, "id":self.id})

    def sex_value(self):
        if self.sex == None:
            return ''
        if self.sex == 'M':
            return '{0}'.format(SEX[0][1])
        elif self.sex == 'F':
            return '{0}'.format(SEX[1][1])

    def level_value(self):
        if self.training_level == None:
            return ''
        if self.training_level == 'N':
            return '{0}'.format(LEVELS[0][1])
        elif self.training_level == 'M':
            return '{0}'.format(LEVELS[1][1])
        elif self.training_level == 'A':
            return '{0}'.format(LEVELS[2][1])
        elif self.training_level == 'P':
            return '{0}'.format(LEVELS[3][1])


@receiver(post_delete, sender=WorkoutTemplate)
def workout_template_post_delete(sender, instance, **kwargs):
    try:
        program_obj = instance.program
    except:
        return
    program_obj.is_active = False
    program_obj.save()
    return


class WsetTemplate(models.Model):
    workout_template = models.ForeignKey(WorkoutTemplate)
    number = models.IntegerField(null=True, blank=True)
    approach_number = models.PositiveIntegerField(default=1)
    rest_time = models.ForeignKey(SettingsRestTime, null=True, blank=False)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '%s | %s' % (self.workout_template, self.number)

    class Meta:
        ordering = ['number']


class TrainingTemplate(models.Model):
    workout_template = models.ForeignKey(WorkoutTemplate)
    workout_occupation = models.ForeignKey(WorkoutOccupation, null=True, blank=True)

subscriptions/templates/subscriptions/DELETE_workouttemplate_detail.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block ajax_food_scripts %}
<script type="text/javascript" src="{% static "panel/assets/js/users/djangoajaxcalls.js" %}"></script>
<script type="text/javascript" src="{% static "panel/assets/js/subscriptions/workout-templates.js" %}"></script>
{% endblock ajax_food_scripts %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12" >
          <div class="panel panel-flat">
              <div class="panel-body">
                <ul class="nav nav-pills nav-stacked col-md-2">
                  {% for wset in object.wsettemplate_set.all %}
                    {% if forloop.first %}
                      <li class="active"><a href="#tab_{{ wset.number }}" id="set_{{ wset.number }}" data-toggle="pill">Сет №{{ wset.number }}</a></li>
                    {% else %}
                      <li><a href="#tab_{{ wset.number }}" data-toggle="pill">Сет №{{ wset.number }}</a></li>
                    {% endif %}
                  {% endfor %}
                </ul>
                <div class="tab-content col-md-10">
                  {% for wset in object.wsettemplate_set.all %}
                    {% if forloop.first %}
                      <div class="tab-pane active" id="tab_{{ wset.number }}" >
                        {% include "panel/includes/subscriptions/trainingform.html" %}
                        {% include "panel/includes/subscriptions/training_template_object_list.html" %}
                      </div>
                    {% else %}
                      <div class="tab-pane" id="tab_{{ wset.number }}">
                           {% include "panel/includes/subscriptions/trainingform.html" %}
                           {% include "panel/includes/subscriptions/training_template_object_list.html" %}
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
          </div>
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/foodprogramtemplate_confirm_delete.html
{% extends "panel/panel_base.html" %} {% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить шаблон: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'subscriptions:program_detail' pk=object.program.id %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/foodprogramtemplate_detail.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% load embed_video_tags %}
{% block ajax_food_scripts %}
  <script type="text/javascript" src="{% static "panel/assets/js/users/djangoajaxcalls.js" %}"></script>
  <script type="text/javascript" src="{% static "panel/assets/js/plugins/autocomplete/jquery.mockjax.js" %}"></script>
  <script type="text/javascript" src="{% static "panel/assets/js/plugins/autocomplete/jquery.autocomplete.js" %}"></script>
  <script type="text/javascript" src="{% static "panel/assets/js/subscriptions/foodtemplate.js" %}"></script>
{% endblock ajax_food_scripts %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12" >
          <div class="panel panel-flat">
              <div class="panel-body">
                <ul class="nav nav-pills nav-stacked col-md-2">
                  {% for day in days %}
                    {% if forloop.first %}
                      <li class="active"><a href="#tab_{{ day.id }}" data-toggle="pill">{{ day }}</a></li>
                    {% else %}
                      <li><a href="#tab_{{ day.id }}" data-toggle="pill">{{ day }}</a></li>
                    {% endif %}
                  {% endfor %}
                </ul>
                <div class="tab-content col-md-10">
                  {% for day in days %}
                    {% if forloop.first %}
                      <div class="tab-pane active activeTab" id="tab_{{ day.id }}" >
                        {% include "panel/includes/subscriptions/foodform.html" %}
                        {% include "panel/includes/subscriptions/food_template_object_list.html" %}
                      </div>
                    {% else %}
                      <div class="tab-pane" id="tab_{{ day.id }}">
                           {% include "panel/includes/subscriptions/foodform.html" %}
                           {% include "panel/includes/subscriptions/food_template_object_list.html" %}
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
          </div>
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/foodprogramtemplate_form.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat panel_form">
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Готово</button>
                </form>
            </div>
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/program_confirm_delete.html
{% extends "panel/panel_base.html" %}{% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'subscriptions:program_list' %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/program_detail.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="panel panel-flat">
        <table class="table datatable-basic datatable-responsive">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Дата создания</th>
                    <th>Название шаблона</th>
                    <th>Пол</th>
                    <th>Уровень физ подготовки</th>
                    <th class="text-center">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% if workout_templates %}
                    {% include "panel/includes/subscriptions/workouttemplate_object_list.html" %}
                {% elif workouts %}
                    {% include "panel/includes/subscriptions/workout_object_list.html" %}
                {% endif %}

                {% if food_templates %}
                    {% include "panel/includes/subscriptions/foodprogram_object_list.html" %}
                {% endif %}

            </tbody>
        </table>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}
{% block callscript %}

{% endblock callscript %}

subscriptions/templates/subscriptions/program_form.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat panel_form">
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Готово</button>
                </form>
            </div>
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

subscriptions/templates/subscriptions/program_list.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    {% include "panel/includes/subscriptions/program_object_list.html" %}
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}
{% block callscript %}
    <script type="text/javascript">
        // Basic initialization
        $('.datatable-basic').DataTable({
            autoWidth: false,
            dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
            language: {
                search: '<span>Фильтр:</span> _INPUT_',
                lengthMenu: '<span>Показать:</span> _MENU_',
                paginate: { 'first': 'Первая', 'last': 'Последняя', 'next': '→', 'previous': '←' }
            },
            drawCallback: function () {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
            },
            preDrawCallback: function() {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
            }
        });
    </script>
{% endblock callscript %}

subscriptions/templates/subscriptions/workouttemplate_form.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block workout_template_scripts %}
<script type="text/javascript" src="{% static "panel/assets/js/users/djangoajaxcalls.js" %}"></script>
<script type="text/javascript" src="{% static "panel/assets/js/subscriptions/workout-templates.js" %}"></script>
{% endblock workout_template_scripts %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12" >
          <div class="panel panel-flat">
              <div class="panel-body">
                <ul class="nav nav-pills nav-stacked col-md-2">
                    <li class="active"><a href="#tab_settings"  data-toggle="pill">Общие настройки</a></li>
                  {% for wset in object.wsettemplate_set.all %}
                      <li><a href="#tab_{{ wset.number }}" data-toggle="pill">Сет №{{ wset.number }}</a></li>
                  {% endfor %}
                </ul>
                <div class="tab-content col-md-10">
                    <div class="tab-pane active" id="tab_settings">
                        <form action="." method="post">
                            {% csrf_token %}
                              {{ form|crispy }}
                              {{ wset_template_form|crispy }}
                              <button type="submit" class="btn btn-default">Сохранить</button>
                        </form>
                    </div>
                  {% for wset in object.wsettemplate_set.all %}
                      <div class="tab-pane" id="tab_{{ wset.number }}">
                           {% include "panel/includes/subscriptions/trainingform.html" %}
                           {% include "panel/includes/subscriptions/training_template_object_list.html" %}
                      </div>
                  {% endfor %}
                </div>
              </div>
          </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12" >
        <div class="panel panel-flat">
            <div class="panel-body">
              <div class="row">
                  <div class="col-md-12 table-responsive" id="exercise_table_list">
                  </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<script type="text/javascript">
    var name = $('#id_name').val();
    $('#id_rest').on('click', function(e) {
          if($('#id_rest').is(":checked")){
              $('#id_name').val('Отдых');
          }
          else {
            $('#id_name').val(name);
            }
      });
</script>
<!-- /content area -->
{% endblock %}