chat/urls.py
# from django.urls import path, re_path

from django.conf.urls import  url
from .views import ThreadView, InboxView

# app_name = 'chat'
# urlpatterns = [
#     path("", InboxView.as_view()),
#     re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
# ]

urlpatterns = [
    url(r'^$', InboxView.as_view(), name="inbox_view"),
    url(r'^(?P<username>[\w.@+-]+)/$', ThreadView.as_view(), name="thread_view"),

]

options/api/urls.py
from django.conf.urls import  url
from options.api.views import ProductListAPIView, ProductRetrieveAPIView, ExerciseListAPIView, ExerciseRetrieveAPIView

urlpatterns = [
    url(r'^products/$', ProductListAPIView.as_view(), name='product_list_api'),
    url(r'^products/(?P<pk>\d+)/$', ProductRetrieveAPIView.as_view(), name='product_detail'),
    url(r'^exercises/$', ExerciseListAPIView.as_view(), name='exercise_list_api'),
    url(r'^exercises/(?P<pk>\d+)/$', ExerciseRetrieveAPIView.as_view(), name='exercise_detail'),


]

options/urls.py
from django.conf.urls import  url
from .views import (
    MuscleCreateView,
    MuscleDeleteView,
    MuscleUpdateView,
    MuscleDetailView,
    ExerciseListView,
    ExerciseCreateView,
    ExerciseDetailView,
    ExerciseDeleteView,
    ExerciseUpdateView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    )
from accounts.views import json_personal_exercise_list, json_exercisecomment_detail, json_product_list, filter_exercise_list
from subscriptions.views import json_template_exercise_list

urlpatterns = [
    url(r'^muscles/$', MuscleCreateView.as_view(), name="muscle_create"),
    url(r'^muscles/(?P<pk>\d+)/$', MuscleDetailView.as_view(), name='muscle_detail'),
    url(r'^muscles/(?P<pk>\d+)/update/$', MuscleUpdateView.as_view(), name='muscle_update'),
    url(r'^muscles/(?P<pk>\d+)/delete/$', MuscleDeleteView.as_view(), name='muscle_delete'),
    url(r'^exercises/$', ExerciseListView.as_view(), name="exercise_list"),
    url(r'^exercises/json/$', json_personal_exercise_list, name="json_personal_exercise_list"),
    url(r'^filter-exercises/json/$', filter_exercise_list, name="filter_exercise_list"),
    url(r'^products/json/$', json_product_list, name="json_product_list"),
    url(r'^exercises/template-json/$', json_template_exercise_list, name="json_template_exercise_list"),
    url(r'^exercises/comments/json/$', json_exercisecomment_detail, name="json_exercisecomment_detail"),
    url(r'^exercises/add/$', ExerciseCreateView.as_view(), name="exercise_create"),
    url(r'^exercises/(?P<pk>\d+)/$', ExerciseDetailView.as_view(), name='exercise_detail'),
    url(r'^exercises/(?P<pk>\d+)/update/$', ExerciseUpdateView.as_view(), name='exercise_update'),
    url(r'^exercises/(?P<pk>\d+)/delete/$', ExerciseDeleteView.as_view(), name='exercise_delete'),
    url(r'^products/$', ProductListView.as_view(), name="product_list"),
    url(r'^products/add/$', ProductCreateView.as_view(), name="product_create"),
    url(r'^products/(?P<pk>\d+)/update/$', ProductUpdateView.as_view(), name='product_update'),
    url(r'^products/(?P<pk>\d+)/delete/$', ProductDeleteView.as_view(), name='product_delete'),
]

options/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from appsettings.models import (
    CompetitionStatus,
    ExerciseCommentName,
    Unit,
    MainMuscle,
    OtherMuscle,
    ExerciseType,
    Biomech,
    Vektor,
    Equipment,
    DifficultyLevel,
    RecipeType,
    RecipeFoodType,
    RecipeAppointment,
    RecipeMode,
    RecipeCooktime,
    RecipeCookmethod,
    PRODUCT_MEAL_CHOICES,
    WorkoutOccupation,
    ModelSex
    )
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from embed_video.fields import EmbedVideoField
from uuslug import slugify
from subscriptions.templates import GENERAL_MUSCLES

# Create your models here.
def fitness_club_upload_location(instance, filename):
    return "fitnessclub/images/%s" % filename

def exercise_upload_location(instance, filename):
    ext = filename.split('.')[1]
    return "exercises/images/%s.%s" % (slugify(instance.name), ext)

def competition_upload_location(instance, filename):
    return "competition/images/%s" % filename

def product_uploads(instance, filename, *args, **kwargs):
    return 'products/%s' % filename

class Muscle(models.Model):
    name = models.CharField('Название группы мышц', max_length=50)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("options:muscle_detail", kwargs={"pk":self.pk})

    def get_delete_url(self):
        return reverse("options:muscle_delete", kwargs = {"pk":self.pk})

    def get_update_url(self):
        return reverse("options:muscle_update", kwargs = {"pk":self.pk})


class Exercise(models.Model):
    approved = models.BooleanField(default=False)
    name = models.CharField(default='', max_length=150)
    content_owner = models.ForeignKey('accounts.Trainer', on_delete=models.SET_NULL, null=True, blank=True)
    workout_occupation = models.ForeignKey(WorkoutOccupation, null=True)
    model_sex = models.ForeignKey(ModelSex, null=True)
    main_muscle = models.ForeignKey(MainMuscle, null=True)
    other_muscle = models.ForeignKey(OtherMuscle, null=True, blank=True)
    exercise_type = models.ForeignKey(ExerciseType, null=True, blank=True)
    biomech = models.ForeignKey(Biomech, null=True, blank=True)
    vektor = models.ForeignKey(Vektor, null=True, blank=True)
    equipment = models.ForeignKey(Equipment, null=True, blank=True)
    difficulty_level = models.ForeignKey(DifficultyLevel, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    video = EmbedVideoField(null=True, blank=True)
    short_video = EmbedVideoField()
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)


    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse("options:exercise_detail", kwargs={"pk":self.pk})

    def get_update_url(self):
        return reverse("options:exercise_update", kwargs = {"pk":self.pk})

    def get_delete_url(self):
        return reverse("options:exercise_delete", kwargs = {"pk":self.pk})

    def get_video_thumb(self):
        try:
            video_code = self.short_video.split('?v=')[1]
        except:
            video_code = self.short_video.split('/')[-1]
        return 'https://img.youtube.com/vi/{0}/2.jpg'.format(video_code)


class FitnessClub(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField(blank=True, null=True)
    video_url = models.URLField(max_length=250, blank=True, null=True)
    private = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse("options:fitnessclub_detail", kwargs={"pk":self.pk})

    def get_update_url(self):
        return reverse("options:fitnessclub_update", kwargs = {"pk":self.pk})

    def get_delete_url(self):
        return reverse("options:fitnessclub_delete", kwargs = {"pk":self.pk})

class FitnessClubImage(models.Model):
    fitnessclub = models.ForeignKey(FitnessClub, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to=fitness_club_upload_location, blank=True, null=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id


class Kbzu1Portion(models.Model):
    weight = models.FloatField(default=0, blank=True, null=True)
    protein = models.FloatField(default=0, blank=False, null=True)
    fat = models.FloatField(default=0, blank=False, null=True)
    carbohydrate = models.FloatField(default=0, blank=False, null=True)
    kkal = models.FloatField(default=0, blank=False, null=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

class Kbzu100g(models.Model):
    weight = models.FloatField(default=0, blank=True, null=True)
    protein = models.FloatField(default=0, blank=False, null=True)
    fat = models.FloatField(default=0, blank=False, null=True)
    carbohydrate = models.FloatField(default=0, blank=False, null=True)
    kkal = models.FloatField(default=0, blank=False, null=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id


class Recipe(models.Model):
    portion_number = models.IntegerField(default=0, blank=True, null=True)
    recipe_type = models.ManyToManyField(RecipeType, blank=True)
    recipe_appointment = models.ManyToManyField(RecipeAppointment, blank=True)
    recipe_food_type = models.ManyToManyField(RecipeFoodType, blank=True)
    recipe_mode = models.ManyToManyField(RecipeMode, blank=True)
    recipe_time = models.ManyToManyField(RecipeCooktime, blank=True)
    recipe_method = models.ManyToManyField(RecipeCookmethod, blank=True)
    ingridients = models.TextField(null=True, blank=True)
    instructions = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id


class Product(models.Model):
    image = models.ImageField(upload_to=product_uploads, default='product_default_img.jpg')
    name = models.CharField(max_length=250, blank=False, null=True)
    product_meal = models.CharField('Тип продукта', max_length=1, choices=PRODUCT_MEAL_CHOICES)
    kbzu_100g = models.ForeignKey(Kbzu100g, blank=True, null=True)
    kbzu_1portion = models.ForeignKey(Kbzu1Portion, null=True, blank=True)
    recipe = models.ForeignKey(Recipe, null=True, blank=True)
    category = models.CharField(max_length=250, blank=False, null=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    def get_update_url(self):
        return reverse("options:product_update", kwargs = {"pk":self.pk})

    def get_delete_url(self):
        return reverse("options:product_delete", kwargs = {"pk":self.pk})

    def recipe_appointment(self):
        if self.recipe:
            return self.recipe.recipe_appointment.name
        return

    def recipe_food_type(self):
        if self.recipe:
            return self.recipe.recipe_food_type.name
        return


class Competition(models.Model):
    name = models.CharField(max_length=250)
    content = models.TextField()
    image = models.ImageField(upload_to=competition_upload_location)
    video = models.URLField(max_length=250, blank=True, null=True)
    start_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    finish_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    status = models.ForeignKey(CompetitionStatus, on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse("options:competition_detail", kwargs={"pk":self.pk})

    def get_update_url(self):
        return reverse("options:competition_update", kwargs = {"pk":self.pk})

    def get_delete_url(self):
        return reverse("options:competition_delete", kwargs = {"pk":self.pk})

options/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from rest_framework import permissions
from sportapps.restconf.permissions import ClientPermissionOnly, LeadPermissionOnly

from options.models import Muscle, Competition, Product, FitnessClub, FitnessClubImage, Exercise
from rest_framework import generics, mixins
from options.api.serializers import MuscleSerializer, ProductSerializer, FitnessClubSerializer, FitnessClubImageSerializer, CompetitionSerializer, ExerciseSerializer


class MuscleListAPIView(generics.ListAPIView):
    permission_classes = [LeadPermissionOnly]
    queryset = Muscle.objects.all()
    serializer_class = MuscleSerializer


class MuscleRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly]
    queryset = Muscle.objects.all()
    serializer_class = MuscleSerializer


class ProductListAPIView(generics.ListAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class FitnessClubListAPIView(generics.ListAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = FitnessClub.objects.all()
    serializer_class = FitnessClubSerializer


class FitnessClubRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = FitnessClub.objects.all()
    serializer_class = FitnessClubSerializer


class FitnessClubImageRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = FitnessClubImage.objects.all()
    serializer_class = FitnessClubImageSerializer

    def get_serializer_context(self, *args, **kwargs):
        return {"request": self.request}


class CompetitionListAPIView(generics.ListAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Competition.objects.all()
    serializer_class = CompetitionSerializer


class CompetitionRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Competition.objects.all()
    serializer_class = CompetitionSerializer

class ExerciseListAPIView(generics.ListAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Exercise.objects.all()
    serializer_class = ExerciseSerializer


class ExerciseRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [LeadPermissionOnly, ClientPermissionOnly]
    queryset = Exercise.objects.all()
    serializer_class = ExerciseSerializer

options/templates/options/competition_confirm_delete.html
{% extends "panel/panel_base.html" %}{% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ title }}</h5>
                </div>
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'options:exercise_list' %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/competition_form.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat panel_form">
                <h1>{{ title }}</h1>
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Готово</button>
                </form>
            </div>
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/exercise_confirm_delete.html
{% extends "panel/panel_base.html" %}{% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ title }}</h5>
                </div>
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'options:exercise_list' %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/exercise_confirm_delete — копия.html
{% extends "panel/panel_base.html" %}{% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ title }}</h5>
                </div>
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'options:exercise_list' %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/exercise_form.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ title }}</h5>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                                    {{ user_form|crispy }}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-default">Готово</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/exercise_list.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    {% include "panel/includes/exercise_object_list.html" %}
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}
{% block callscript %}
    <script type="text/javascript">
        // Basic initialization
        $('.datatable-basic').DataTable({
            processing: "Загружаем...",
            autoWidth: false,
            dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
            language: {
                search: '<span>Фильтр:</span> _INPUT_',
                lengthMenu: '<span>Показать:</span> _MENU_',
                paginate: { 'first': 'Первая', 'last': 'Последняя', 'next': '→', 'previous': '←' }
            },
            drawCallback: function () {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
            },
            preDrawCallback: function() {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
            }
        });
    </script>
{% endblock callscript %}

options/templates/options/exercise_list_thumb.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <!-- Search field -->
    <div class="panel">
        <div class="panel-body">
            <form action="#" class="main-search">
                <div class="input-group content-group">
                    <div class="has-feedback has-feedback-left">
                        <input type="text" class="form-control input-xlg" placeholder="Каталог упражнений {% if object_list %}({{ object_list.count }}) {% endif %}" name="q" id="s" value="{{ request.GET.q }}">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-muted text-size-base"></i>
                        </div>
                    </div>

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary btn-xlg">Поиск</button>
                    </div>
                </div>

                <div class="row search-option-buttons">
                    <div class="col-sm-10">
                        <div class="category-container">
                            По мышцам: {% for obj in muscles %} <a href="{{ obj.get_absolute_url }}">{{ obj }}
                            ({{ obj.exercise_set.all.count }})
                            </a> {% if not forloop.last %}|{% endif %} {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-2 text-right">
                        <ul class="list-inline no-margin-bottom">
                            <li><a href="{% url 'options:exercise_list' %}" class="btn btn-link"><i class="icon-reload-alt position-left"></i> Сбросить поиск</a></li>
                        </ul>
                    </div>
                </div>
            </form>
        </div>
    </div>
                        <!-- /search field -->
    {% include "panel/includes/exercise_object_list.html" %}
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/fitnessclub_confirm_delete.html
{% extends "panel/panel_base.html" %}{% load staticfiles %}{% load i18n %} {% block head_extra %}
{% load crispy_forms_tags %}
{% endblock head_extra %} {% block content %}{{ form.media }}
{% include "panel/includes/header.html" %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ title }}</h5>
                </div>
                <div class="panel-body">
                    Действие необратимо.
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-11 simple-data-form">
                               <form action="" method="post">{% csrf_token %}
                                   <p>Вы, действительно, хотите удалить: "{{ object.name }}"?</p>
                                   <input type="submit" class="btn btn-danger" value="Подтвердить" />
                                   <a href="{% url 'options:exercise_list' %}" class="btn btn-default">Отмена</a>
                               </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
    </div>
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}

options/templates/options/fitnessclub_list.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    {% include "panel/includes/fitnessclub_object_list.html" %}
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}
{% block callscript %}
    <script type="text/javascript">
        // Basic initialization
        $('.datatable-basic').DataTable({
            autoWidth: false,
            dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
            language: {
                search: '<span>Фильтр:</span> _INPUT_',
                lengthMenu: '<span>Показать:</span> _MENU_',
                paginate: { 'first': 'Первая', 'last': 'Последняя', 'next': '→', 'previous': '←' }
            },
            drawCallback: function () {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
            },
            preDrawCallback: function() {
                $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
            }
        });
    </script>
{% endblock callscript %}

options/templates/options/muscle_detail.html
{% extends "panel/panel_base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
{% include "panel/includes/header.html" %}
<div class="content">
    <!-- Search field -->
    <div class="panel">
        <div class="panel-body">
            <form action="#" class="main-search">
                <div class="input-group content-group">
                    <div class="has-feedback has-feedback-left">
                        <input type="text" class="form-control input-xlg" placeholder="Каталог упражнений {% if queryset %}({{ queryset.count }}) {% endif %}" name="q" id="s" value="{{ request.GET.q }}">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-muted text-size-base"></i>
                        </div>
                    </div>

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary btn-xlg">Поиск</button>
                    </div>
                </div>

                <div class="row search-option-buttons">
                    <div class="col-sm-10">
                        <div class="category-container">
                            По мышцам: {% for obj in muscles %} <a href="{{ obj.get_absolute_url }}">{{ obj }}
                            ({{ obj.exercise_set.all.count }})
                            </a> {% if not forloop.last %}|{% endif %} {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-2 text-right">
                        <ul class="list-inline no-margin-bottom">
                            <li><a href="{% url 'options:exercise_list' %}" class="btn btn-link"><i class="icon-reload-alt position-left"></i> Сбросить поиск</a></li>
                        </ul>
                    </div>
                </div>
            </form>
        </div>
    </div>
                        <!-- /search field -->
    {% include "panel/includes/exercise_object_list.html" %}
    {% include "panel/footer.html" %}
</div>
<!-- /content area -->
{% endblock %}